// All 59 clinical assessment questions mapped to backend field names
// Options: value maps exactly to what analyze_clinical() expects in api/index.py

export const SECTIONS = [
  {
    id: 'personal',
    title: 'Personal Information',
    icon: '👤',
    fields: [
      { key: 'name',   label: 'Full Name',   type: 'text',   placeholder: 'Your full name' },
      { key: 'age',    label: 'Age',         type: 'number', placeholder: 'Your age' },
      { key: 'gender', label: 'Gender',      type: 'select',
        options: [{ value: 'male', label: 'Male' }, { value: 'female', label: 'Female' }, { value: 'other', label: 'Other' }] },
      { key: 'weight', label: 'Weight (kg)', type: 'number', placeholder: 'e.g. 65' },
      { key: 'height', label: 'Height (cm)', type: 'number', placeholder: 'e.g. 170' },
    ],
  },
  {
    id: 'body_structure',
    title: 'Body Structure',
    icon: '🏗️',
    questions: [
      { key: 'body_frame', label: 'Body Frame',
        options: [{ value: 'thin', label: 'Thin / Narrow', icon: '🌿' }, { value: 'medium', label: 'Medium / Athletic', icon: '💪' }, { value: 'heavy', label: 'Heavy / Wide', icon: '🏔️' }] },
      { key: 'body_build', label: 'Body Build',
        options: [{ value: 'lean', label: 'Lean / Weakly developed', icon: '🍃' }, { value: 'muscular', label: 'Muscular / Moderate', icon: '⚡' }, { value: 'stocky', label: 'Stocky / Well developed', icon: '🪨' }] },
      { key: 'muscle_tone', label: 'Muscle Tone',
        options: [{ value: 'low', label: 'Low / Thin musculature', icon: '🌾' }, { value: 'medium', label: 'Medium / Soft', icon: '🌊' }, { value: 'high', label: 'High / Firm', icon: '🔩' }] },
      { key: 'weight_tendency', label: 'Weight Tendency',
        options: [{ value: 'hard_to_gain', label: 'Hard to gain weight', icon: '🍃' }, { value: 'stable', label: 'Stable weight', icon: '⚖️' }, { value: 'easy_to_gain', label: 'Easy to gain weight', icon: '🌰' }] },
      { key: 'joints', label: 'Joints Appearance',
        options: [{ value: 'prominent', label: 'Prominent / Visible', icon: '🦴' }, { value: 'normal', label: 'Normal', icon: '✅' }, { value: 'well_covered', label: 'Well covered / Padded', icon: '🛡️' }] },
      { key: 'veins', label: 'Veins Visibility',
        options: [{ value: 'prominent', label: 'Prominent / Visible', icon: '🔵' }, { value: 'visible', label: 'Slightly visible', icon: '🟦' }, { value: 'hidden', label: 'Hidden / Not visible', icon: '⬜' }] },
      { key: 'bone_structure', label: 'Bone Structure',
        options: [{ value: 'light', label: 'Light / Delicate', icon: '🪶' }, { value: 'medium', label: 'Medium', icon: '🦷' }, { value: 'heavy', label: 'Heavy / Dense', icon: '🪨' }] },
    ],
  },
  {
    id: 'skin_hair',
    title: 'Skin & Hair',
    icon: '✨',
    questions: [
      { key: 'skin_type', label: 'Skin Type',
        options: [{ value: 'dry', label: 'Dry / Rough', icon: '🏜️' }, { value: 'sensitive', label: 'Sensitive / Reddish', icon: '🌹' }, { value: 'oily', label: 'Oily / Smooth', icon: '💧' }] },
      { key: 'skin_texture', label: 'Skin Texture',
        options: [{ value: 'rough', label: 'Rough / Cracked', icon: '🪨' }, { value: 'soft', label: 'Soft / Delicate', icon: '🌸' }, { value: 'smooth', label: 'Smooth / Thick', icon: '🪞' }] },
      { key: 'skin_temperature', label: 'Skin Temperature',
        options: [{ value: 'cold', label: 'Usually cold', icon: '❄️' }, { value: 'warm', label: 'Usually warm / hot', icon: '🔥' }] },
      { key: 'complexion', label: 'Complexion',
        options: [{ value: 'dark', label: 'Dark / Dusky', icon: '🌑' }, { value: 'fair', label: 'Fair / Bright', icon: '🌕' }, { value: 'pale', label: 'Pale / Dull', icon: '🌫️' }] },
      { key: 'skin_luster', label: 'Skin Luster',
        options: [{ value: 'dull', label: 'Dull / Dry', icon: '🌑' }, { value: 'radiant', label: 'Radiant / Glowing', icon: '✨' }, { value: 'glowing', label: 'Naturally glowing', icon: '🌟' }] },
      { key: 'hair_type', label: 'Hair Type',
        options: [{ value: 'dry', label: 'Dry / Frizzy', icon: '🌾' }, { value: 'thin', label: 'Thin / Fine', icon: '🍃' }, { value: 'thick', label: 'Thick / Lustrous', icon: '🌿' }] },
      { key: 'hair_texture', label: 'Hair Texture',
        options: [{ value: 'rough', label: 'Rough / Coarse', icon: '🪨' }, { value: 'fine', label: 'Fine / Silky', icon: '🧵' }, { value: 'smooth', label: 'Smooth / Wavy', icon: '🌊' }] },
      { key: 'nails', label: 'Nails',
        options: [{ value: 'brittle', label: 'Brittle / Break easily', icon: '💔' }, { value: 'soft', label: 'Soft / Pinkish', icon: '🌸' }, { value: 'strong', label: 'Strong / Thick', icon: '💪' }] },
    ],
  },
  {
    id: 'digestion',
    title: 'Appetite & Digestion',
    icon: '🔥',
    questions: [
      { key: 'appetite', label: 'Appetite',
        options: [{ value: 'irregular', label: 'Irregular / Variable', icon: '🎲' }, { value: 'strong', label: 'Strong / Sharp', icon: '🔥' }, { value: 'low', label: 'Low / Mild', icon: '🌿' }] },
      { key: 'hunger', label: 'Hunger Pattern',
        options: [{ value: 'variable', label: 'Variable / Unpredictable', icon: '🎲' }, { value: 'intense', label: 'Intense / Cannot skip meals', icon: '⚡' }, { value: 'mild', label: 'Mild / Can skip meals', icon: '🌙' }] },
      { key: 'thirst', label: 'Thirst Level',
        options: [{ value: 'variable', label: 'Variable', icon: '🎲' }, { value: 'high', label: 'High / Always thirsty', icon: '💧' }, { value: 'low', label: 'Low / Rarely thirsty', icon: '🌵' }] },
      { key: 'digestion', label: 'Digestion Speed',
        options: [{ value: 'irregular', label: 'Irregular / Unpredictable', icon: '🎲' }, { value: 'fast', label: 'Fast / Quick', icon: '⚡' }, { value: 'slow', label: 'Slow / Heavy', icon: '🐢' }] },
      { key: 'bowel', label: 'Bowel Movement',
        options: [{ value: 'constipation', label: 'Constipation / Hard stools', icon: '🪨' }, { value: 'loose', label: 'Loose / Frequent', icon: '💧' }, { value: 'regular', label: 'Regular / Normal', icon: '✅' }, { value: 'heavy', label: 'Heavy / Bulky', icon: '🏔️' }] },
      { key: 'gas', label: 'Gas / Bloating',
        options: [{ value: 'frequent', label: 'Frequent / Excessive', icon: '💨' }, { value: 'occasional', label: 'Occasional', icon: '🌬️' }, { value: 'none', label: 'Rarely / None', icon: '✅' }] },
      { key: 'food_preference', label: 'Food Preference',
        options: [{ value: 'warm', label: 'Warm / Cooked foods', icon: '♨️' }, { value: 'cold', label: 'Cold / Raw foods', icon: '❄️' }, { value: 'spicy', label: 'Spicy / Pungent', icon: '🌶️' }] },
      { key: 'metabolism', label: 'Metabolism',
        options: [{ value: 'fast', label: 'Fast / High', icon: '⚡' }, { value: 'moderate', label: 'Moderate / Balanced', icon: '⚖️' }, { value: 'slow', label: 'Slow / Low', icon: '🐢' }] },
    ],
  },
  {
    id: 'lifestyle',
    title: 'Sleep & Energy',
    icon: '🌙',
    questions: [
      { key: 'sleep_pattern', label: 'Sleep Pattern',
        options: [{ value: 'light', label: 'Light / Disturbed', icon: '😴' }, { value: 'moderate', label: 'Moderate / Normal', icon: '🌙' }, { value: 'deep', label: 'Deep / Heavy', icon: '💤' }] },
      { key: 'sleep_duration', label: 'Sleep Duration',
        options: [{ value: 'less_6', label: 'Less than 6 hours', icon: '⏰' }, { value: '6_8', label: '6–8 hours', icon: '✅' }, { value: 'more_8', label: 'More than 8 hours', icon: '🛌' }] },
      { key: 'dreams', label: 'Dreams',
        options: [{ value: 'active', label: 'Active / Vivid / Fearful', icon: '🌪️' }, { value: 'colorful', label: 'Colorful / Passionate', icon: '🎨' }, { value: 'few', label: 'Few / Calm / Watery', icon: '🌊' }] },
      { key: 'energy_level', label: 'Energy Level',
        options: [{ value: 'variable', label: 'Variable / Bursts & crashes', icon: '⚡' }, { value: 'moderate', label: 'Moderate / Focused', icon: '🎯' }, { value: 'steady', label: 'Steady / Consistent', icon: '🌊' }] },
      { key: 'stamina', label: 'Stamina',
        options: [{ value: 'low', label: 'Low / Tires quickly', icon: '🍃' }, { value: 'medium', label: 'Medium / Average', icon: '⚖️' }, { value: 'high', label: 'High / Enduring', icon: '🏔️' }] },
      { key: 'physical_activity', label: 'Physical Activity Style',
        options: [{ value: 'restless', label: 'Restless / Always moving', icon: '🌪️' }, { value: 'moderate', label: 'Moderate / Purposeful', icon: '🚶' }, { value: 'slow', label: 'Slow / Deliberate', icon: '🐢' }] },
      { key: 'exercise_tolerance', label: 'Exercise Tolerance',
        options: [{ value: 'low', label: 'Low / Easily fatigued', icon: '😓' }, { value: 'high', label: 'High / Intense preferred', icon: '💪' }, { value: 'moderate', label: 'Moderate / Steady', icon: '🚴' }] },
    ],
  },
  {
    id: 'body_response',
    title: 'Body Response & Climate',
    icon: '🌡️',
    questions: [
      { key: 'sweat', label: 'Sweating',
        options: [{ value: 'minimal', label: 'Minimal / Rarely sweats', icon: '🌵' }, { value: 'profuse', label: 'Profuse / Excessive', icon: '💦' }, { value: 'moderate', label: 'Moderate / Normal', icon: '💧' }] },
      { key: 'body_odor', label: 'Body Odor',
        options: [{ value: 'minimal', label: 'Minimal / Neutral', icon: '🌿' }, { value: 'strong', label: 'Strong / Pungent', icon: '🔥' }, { value: 'mild', label: 'Mild / Sweet', icon: '🌸' }] },
      { key: 'weather_preference', label: 'Weather Preference',
        options: [{ value: 'warm', label: 'Prefer warm weather', icon: '☀️' }, { value: 'cool', label: 'Prefer cool weather', icon: '❄️' }] },
      { key: 'season_discomfort', label: 'Season of Discomfort',
        options: [{ value: 'winter', label: 'Winter / Cold & dry', icon: '❄️' }, { value: 'summer', label: 'Summer / Hot & humid', icon: '☀️' }, { value: 'spring', label: 'Spring / Damp & cloudy', icon: '🌧️' }] },
      { key: 'immunity', label: 'Immunity',
        options: [{ value: 'weak', label: 'Weak / Frequent illness', icon: '😷' }, { value: 'moderate', label: 'Moderate / Average', icon: '⚖️' }, { value: 'strong', label: 'Strong / Rarely ill', icon: '🛡️' }] },
      { key: 'disease_tendency', label: 'Disease Tendency',
        options: [{ value: 'nervous', label: 'Nervous / Anxiety disorders', icon: '😰' }, { value: 'inflammatory', label: 'Inflammatory / Infections', icon: '🔥' }, { value: 'congestion', label: 'Congestion / Weight issues', icon: '🌊' }] },
    ],
  },
  {
    id: 'speech_mind',
    title: 'Speech & Mind',
    icon: '🧠',
    questions: [
      { key: 'speech_pace', label: 'Speech Pace',
        options: [{ value: 'fast', label: 'Fast / Rapid', icon: '⚡' }, { value: 'moderate', label: 'Moderate / Clear', icon: '🎯' }, { value: 'slow', label: 'Slow / Deliberate', icon: '🐢' }] },
      { key: 'voice_quality', label: 'Voice Quality',
        options: [{ value: 'weak', label: 'Weak / Hoarse', icon: '🌬️' }, { value: 'sharp', label: 'Sharp / Penetrating', icon: '🔊' }, { value: 'deep', label: 'Deep / Resonant', icon: '🎵' }] },
      { key: 'communication', label: 'Communication Style',
        options: [{ value: 'talkative', label: 'Talkative / Enthusiastic', icon: '💬' }, { value: 'precise', label: 'Precise / Articulate', icon: '🎯' }, { value: 'reserved', label: 'Reserved / Thoughtful', icon: '🤫' }] },
      { key: 'movements', label: 'Body Movements',
        options: [{ value: 'quick', label: 'Quick / Restless', icon: '⚡' }, { value: 'purposeful', label: 'Purposeful / Confident', icon: '🎯' }, { value: 'slow', label: 'Slow / Graceful', icon: '🌊' }] },
      { key: 'mental_state', label: 'Mental State',
        options: [{ value: 'anxious', label: 'Anxious / Worried', icon: '😰' }, { value: 'focused', label: 'Focused / Intense', icon: '🎯' }, { value: 'calm', label: 'Calm / Relaxed', icon: '🧘' }] },
      { key: 'memory', label: 'Memory',
        options: [{ value: 'quick_forget', label: 'Quick to learn, quick to forget', icon: '🌪️' }, { value: 'sharp', label: 'Sharp / Precise', icon: '🔬' }, { value: 'slow_retain', label: 'Slow to learn, long retention', icon: '🏔️' }] },
      { key: 'learning', label: 'Learning Style',
        options: [{ value: 'quick', label: 'Quick / Grasps fast', icon: '⚡' }, { value: 'moderate', label: 'Moderate / Methodical', icon: '📚' }, { value: 'slow', label: 'Slow / Thorough', icon: '🐢' }] },
      { key: 'concentration', label: 'Concentration',
        options: [{ value: 'poor', label: 'Poor / Easily distracted', icon: '🌪️' }, { value: 'good', label: 'Good / Focused', icon: '🎯' }, { value: 'excellent', label: 'Excellent / Deep focus', icon: '🔬' }] },
      { key: 'decision_making', label: 'Decision Making',
        options: [{ value: 'quick', label: 'Quick / Impulsive', icon: '⚡' }, { value: 'analytical', label: 'Analytical / Decisive', icon: '🧮' }, { value: 'slow', label: 'Slow / Careful', icon: '🐢' }] },
    ],
  },
  {
    id: 'behavior',
    title: 'Behavior & Emotions',
    icon: '💫',
    questions: [
      { key: 'emotional_response', label: 'Emotional Response',
        options: [{ value: 'fearful', label: 'Fear / Anxiety / Worry', icon: '😰' }, { value: 'angry', label: 'Anger / Irritation', icon: '😤' }, { value: 'attached', label: 'Attachment / Possessiveness', icon: '🤗' }] },
      { key: 'stress_response', label: 'Stress Response',
        options: [{ value: 'anxious', label: 'Anxious / Nervous', icon: '😰' }, { value: 'irritable', label: 'Irritable / Aggressive', icon: '😤' }, { value: 'withdrawn', label: 'Withdrawn / Lethargic', icon: '😶' }] },
    ],
  },
  {
    id: 'additional',
    title: 'Additional Characteristics',
    icon: '🔍',
    questions: [
      { key: 'teeth_gums', label: 'Teeth & Gums',
        options: [{ value: 'weak', label: 'Weak / Sensitive / Receding', icon: '😬' }, { value: 'normal', label: 'Normal / Average', icon: '✅' }, { value: 'strong', label: 'Strong / Healthy', icon: '💪' }] },
      { key: 'eyes_appearance', label: 'Eyes Appearance',
        options: [{ value: 'small', label: 'Small / Dry / Nervous', icon: '👁️' }, { value: 'medium', label: 'Medium / Sharp / Bright', icon: '🔬' }, { value: 'large', label: 'Large / Moist / Calm', icon: '🌊' }] },
      { key: 'lips_condition', label: 'Lips Condition',
        options: [{ value: 'dry', label: 'Dry / Cracked / Thin', icon: '🏜️' }, { value: 'normal', label: 'Normal / Pinkish', icon: '✅' }, { value: 'moist', label: 'Moist / Full / Smooth', icon: '💧' }] },
      { key: 'temp_regulation', label: 'Temperature Regulation',
        options: [{ value: 'poor', label: 'Poor (always cold or hot)', icon: '🌡️' }, { value: 'moderate', label: 'Moderate', icon: '⚖️' }, { value: 'good', label: 'Good adaptation', icon: '✅' }] },
      { key: 'pain_tolerance', label: 'Pain Tolerance',
        options: [{ value: 'low', label: 'Low / Sensitive', icon: '😣' }, { value: 'medium', label: 'Medium / Average', icon: '⚖️' }, { value: 'high', label: 'High / Tolerant', icon: '💪' }] },
      { key: 'healing_speed', label: 'Healing Speed',
        options: [{ value: 'slow', label: 'Slow / Takes long', icon: '🐢' }, { value: 'moderate', label: 'Moderate / Average', icon: '⚖️' }, { value: 'fast', label: 'Fast / Quick recovery', icon: '⚡' }] },
    ],
  },
]

// Flatten all question keys for progress tracking
export const ALL_QUESTION_KEYS = SECTIONS.flatMap(s =>
  s.fields ? s.fields.map(f => f.key) : s.questions.map(q => q.key)
)

export const TOTAL_QUESTIONS = ALL_QUESTION_KEYS.length  // 59
